### ISSUE TITLE
Distance matrix 'X' must be symmetric

### ISSUE THREAD

**Issue by SofoklisMouratidis** [MattJBritton/ExquisiteCorrpse#2]
(Google Colab Runtime)

**ERROR:**
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-16-5ea010506674> in <module>()
      7 # Create Heatmap
      8 
----> 9 visualize_feature_correlation(train_set, "heatmap").properties(title="Transcoding Heat Map")

2 frames

<ipython-input-2-b9dc3bb7f10e> in visualize_feature_correlation(data, chart_type, target_name, cluster_scope, user_defined_clusters)
      7         corr = corr.drop(target_name, axis=1).drop(target_name, axis=0)
      8     default_feature_order = sorted(list(df.columns))
----> 9     corr_condensed = hc.distance.squareform(1 - np.abs(df.corr()) ) # convert to condensed
     10     z = hc.linkage(corr_condensed, method='average');
     11     feature_order = hc.dendrogram(z, labels=df.columns, no_plot=True)["ivl"];

/usr/local/lib/python3.7/dist-packages/scipy/spatial/distance.py in squareform(X, force, checks)
   2191             raise ValueError('The matrix argument must be square.')
   2192         if checks:
-> 2193             is_valid_dm(X, throw=True, name='X')
   2194 
   2195         # One-side of the dimensions is set here.

/usr/local/lib/python3.7/dist-packages/scipy/spatial/distance.py in is_valid_dm(D, tol, throw, name, warning)
   2267                 if name:
   2268                     raise ValueError(('Distance matrix \'%s\' must be '
-> 2269                                      'symmetric.') % name)
   2270                 else:
   2271                     raise ValueError('Distance matrix must be symmetric.')

ValueError: Distance matrix 'X' must be symmetric.

**Comment by MattJBritton** [comment]
Hi @SofoklisMouratidis, first of all, thanks for taking the time to investigate my project.

Unfortunately, I'm not able to replicate your issue. It looks like Pandas.DataFrame.corr() is producing an asymmetrical matrix, which I've not seen happen before. Can you provide your data set, or sample data set that serves as a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)? Alternately, just looking at `{your_dataset}.corr()` could be helpful.

**Comment by SofoklisMouratidis** [comment]
Thank you for the tip, the issue is solved.

The dataset I've been using is  made from data found [here](https://archive.ics.uci.edu/ml/datasets/Online+Video+Characteristics+and+Transcoding+Time+Dataset), about 40 columns. There was a column with 0s that went unnoticed.
